name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Detect changes in source files
  changes:
    permissions:
      pull-requests: read
      contents: read
    uses: ./.github/workflows/detect-changes.yml

  lint:
    needs: [changes]
    if: |
      needs.changes.outputs.androidTest == 'true' ||
      needs.changes.outputs.main == 'true' ||
      needs.changes.outputs.test == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint check
        run: ./gradlew lintDebug

      - name: Upload lint results report (html)
        uses: actions/upload-artifact@v3
        with:
          name: lint-results-debug.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    if: |
      needs.changes.outputs.androidTest == 'true' ||
      needs.changes.outputs.main == 'true' ||
      needs.changes.outputs.test == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload unit test summary report (debug)
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report-debug
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Upload unit test summary report (release)
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report-release
          path: app/build/reports/tests/testReleaseUnitTest/

  instrumentation-test:
    needs: [lint]
    if: |
      needs.changes.outputs.androidTest == 'true' ||
      needs.changes.outputs.main == 'true' ||
      needs.changes.outputs.test == 'true'
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [33, 34]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest

      - name: Upload instrumentation test summary report
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation-test-report
          path: app/build/reports/androidTests/connected/